drivers/usb: gadget: function: Fix missing read_spinlock variable
../drivers/usb/gadget/function/f_hid.c:511:27: error: no member named 'read_spinlock' in 'struct f_hidg'
        spin_lock_irqsave(&hidg->read_spinlock, flags);
                           ~~~~  ^
../include/linux/spinlock.h:337:39: note: expanded from macro 'spin_lock_irqsave'
        raw_spin_lock_irqsave(spinlock_check(lock), flags);     \
                                             ^~~~
../include/linux/spinlock.h:208:34: note: expanded from macro 'raw_spin_lock_irqsave'
                flags = _raw_spin_lock_irqsave(lock);   \
                                               ^~~~
../drivers/usb/gadget/function/f_hid.c:517:32: error: no member named 'read_spinlock' in 'struct f_hidg'
        spin_unlock_irqrestore(&hidg->read_spinlock, flags);